version: '2'
services:
    angularmaps-app:
        image: angularmaps
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://angularmaps-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=angularmaps
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularmaps-mongodb:
        extends:
            file: mongodb.yml
            service: angularmaps-mongodb
